### PR TITLE
Add basic support for Swift Package Manager

### PR DESCRIPTION
**Pull request by carsonxyz**
Adding basic support for people that want to use this library with SwiftPM.

### CODE REVIEW

**Comment by carsonxyz** [comment]
It would be lovely to get this merged in right away. The only thing you will need to do is update your latest release tag to include this file or make a new release so people that use SwiftPM can target a specific version. Thanks!

**Comment by kizitonwose** [comment]
Thank you very much for adding SPM support. I don't fully understand SPM. What needs to be done when a new version of the lib is released? Also, I see that the added `Package.swift` file has `swift-tools-version:4.2` even though the project currently uses swift 5, any reason for this?

**Comment by carsonxyz** [comment]
Good eye. I updated the version to 5.0. The only thing that needs to be done on your part now is tag a new release from master after merging so that the Package.swift file is included.

**Comment by kizitonwose** [comment]
So SPM basically works with tags. Will merge right away!

**Pull request merged**
