### PR TITLE
Add Curacao; Remove unused flag (AN.png)

### PR DESCRIPTION
**Pull request by zfoltin**
https://en.wikipedia.org/wiki/Cura%C3%A7ao

### CODE REVIEW

**Comment by zfoltin** [comment]
Hi @kizitonwose, any chance you could look at this PR and merge/publish? It would be highly appreciated 🙏

**Comment by kizitonwose** [comment]
Sorry for the delay, merging now and publishing in a few minutes.

**Comment by kizitonwose** [comment]
Now released in [3.1.1](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.1.1) 🚀

**Comment by zfoltin** [comment]
Thanks a bunch @kizitonwose 💯

**Pull request merged**
