### PR TITLE
Updated project to Swift 5.0

### PR DESCRIPTION
**Pull request by serjooo**
- Protocol conformances to public protocols must conform to methods with a public identifier as well
- Changed podspec file to update Swift version as well

### CODE REVIEW

**Comment by kizitonwose** [comment]
Thank you for contributing. You need to change the swift verison in the `.swift-version` file in the root directory as well.

**Comment by serjooo** [comment]
@kizitonwose I was going to change that, but I wondered why it wasn't updated for Swift 4.2, so didn't change it.

**Comment by kizitonwose** [comment]
I think it's only necessary for major swift releases. I'm not sure though.
By the way, I wonder if it's best to release this swift 5 update on a separate branch for now. I guess not many people have updated their projects to swift 5 at this time.

**Comment by serjooo** [comment]
I think it makes sense to branch out. It also depends on if you have new features to push out and would like it to be available for the Swift 4.2 version. If not you can always tag the latest Swift 4.2 version and then do a major increment version and tag that for Swift 5.0 and while doing a pod install a developer could mention the version of 4.2 or 5.0 depending on their needs. However, I do have to mention I'm not entirely sure if this scheme works as I just recently released my first ever pod.

**Comment by kizitonwose** [comment]
CocoaPods and Carthage handle dependency version resolution pretty well. I think releasing separately makes sense as well. I'll do that in the coming days. 
Once again, thank you for the PR.

**Pull request merged**
