### PR TITLE
Add country name to view

### PR DESCRIPTION
**Pull request by itsniper**
Great library and almost perfect for what I needed. My need was for a country picker for a sign-up form so additionally, I needed the full country name in the view. Added this as an additional flag that can be set. Also, updated the demo app and README accordingly. Hope this can be helpful for someone else as well. Cheers!

### CODE REVIEW

**Comment by itsniper** [comment]
Oh yes ... I also fixed an auto-layout issue in the demo app where "SEARCH BAR POSITION" was getting clipped vertically.

**Comment by kizitonwose** [comment]
Thank you very much for contributing. I like the name addition although, in the current logic, it will be shown only if the country and phone code properties are set to false. I think we can have it in such a way that country name and code and dependent on each other. That is, if code is enabled, name is disabled and vice versa. This way, if a user really wants, they can have [Flag][Name][Phone code] on the view.

I'll just merge this and make the "if-else" changes needed in the dev branch.

Once again, thank you!

**Comment by kizitonwose** [comment]
Now available in [3.0.9](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.0.9) 🚀

**Comment by itsniper** [comment]
I like that idea 👍. I'm happy to contribute to a well-maintained library, and I appreciate the quick response!

**Pull request merged**
