### PR TITLE
Update Tokelau's flag

### PR DESCRIPTION
**Pull request by zfoltin**
Based on https://en.wikipedia.org/wiki/Tokelau

### CODE REVIEW

**Comment by zfoltin** [comment]
Hey @kizitonwose any chance you can review this and merge & release please?

**Comment by kizitonwose** [comment]
> Hey @kizitonwose any chance you can review this and merge & release please?

Hi, thanks for the fix. Is it urgent? I plan to take a look at this repo in the weekend since I haven't done that in a while. Would it be late by then?

**Comment by zfoltin** [comment]
Thanks a ton @kizitonwose 😊 It's not super urgent. A release next week or so would be greatly appreciated 🙇

**Comment by kizitonwose** [comment]
@zfoltin Alright 👍

**Pull request merged**
