### PR TITLE
Adds new customization to CountryPickerViewController through the ContryPickerViewDatasource

### PR DESCRIPTION
**Pull request by serjooo**
- Added a method to allow to customize SectionHeaderTitleTextColor
- Added a method  to allow to customize the SearchBar background color. It also sets the background color of the UISearchViewController to the same color.

### CODE REVIEW

**Comment by kizitonwose** [comment]
Thanks for contributing! Any reason why we have to use the same color for the UISearchViewController and SearchBar backgrounds?

**Comment by serjooo** [comment]
No reason. I should actually separate them into another method. I'll add that change right now

**Comment by kizitonwose** [comment]
I think if we keep adding customization methods to `CountryPickerViewDataSource`, then we are going to end up with a lot of methods for everyone's use case. The `CountryPickerViewDelegate` protocol already has `willShow` and `didShow` methods which provide access to the internal `CountryPickerViewController`. 

If we use less strict access modifiers for customizable properties in the `CountryPickerViewController` class, then users can customize these properties whichever way they prefer. For your use case, we could just make the `searchController` property public and that saves us two datasource methods(and possibly more in the future).

**Comment by serjooo** [comment]
@kizitonwose I completely agree; however, I thought you had put strict access modifiers for some reason, so I continued with the initial API design decisions. Also, the `willShow` and `didShow` methods make public the `superclass` of the `CountryPickerViewController`, which is the `UITableViewController`. Also, I thought this was done on purpose.

If you don't mind making `CountryPickerViewController` accessible from those methods then everything should be in line and as you said everyone can customize as they see fit in those methods.

**Comment by kizitonwose** [comment]
@serjooo I don't mind making CountryPickerViewController accessible from the delegates, so let's proceed with that. Are you going to make the necessary changes?

**Comment by serjooo** [comment]
Yes, I'll make these changes tonight!

**Comment by serjooo** [comment]
@kizitonwose Sorry I'm late on this got really busy. Can you please review the changes I made and the updates I made to the README. Thank you!

**Comment by kizitonwose** [comment]
Everything looks good. I'll merge this into the `public-view-controller` branch then publish a new release on cocoapods.org before finally merging into master. This is so that the information on the README in the master branch matches the library version available on cocoapods since that's what people see when they visit the repo.
 
Thank you very much for contributing.

**Comment by serjooo** [comment]
@kizitonwose Just wondering when you'll be able to merge this into master. I currently need it for one of my projects. Or should I just use the `public-view-controller` branch?

**Comment by kizitonwose** [comment]
@serjooo Yes, please use the `public-view-controller` branch for now.

**Pull request merged**
