### PR TITLE
Fixed minor typos

### PR DESCRIPTION
**Pull request by ss18**
country's, programmaticaly & neccessary

### CODE REVIEW

**Review by kizitonwose — CHANGES_REQUESTED** [review]
Hello @ss18, thanks for contributing. Singular possessive of `country` is `country's`. All other changes are okay except this(country's to countries). Could you please fix this?

**Comment by ss18** [comment]
@kizitonwose Hello, I can revert word "country's" back. But in my opinion it makes no sense, since you have used already word "countries" in sources a lot, e.g. DemoViewController.swift, CountryPickerView.podspec.json etc. So, fix I made, makes it a bit more consistent.

**Comment by kizitonwose** [comment]
In those cases(podspec, DemoViewController etc), `countries` is correct because it's used as the plural of `country`.

**Comment by ss18** [comment]
got it. Revert it back.

**Review by kizitonwose — APPROVED** [review]

**Pull request merged**
